spring:
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3306/gulimall_oms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-order
  cloud:
    nacos:
      server-addr: localhost:8848


server:
  port: 9000

mybatis-plus:
    type-aliases-package: com.ledger.gulimall.order.entity
    mapper-locations: classpath:/mapper/**/*.xml
